name: Compile Typst Posters
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: latest

      - name: Compile Poster Layout 1
        run: cd posters && typst compile poster-layout1.typ poster-layout1.pdf

      - name: Compile Poster Layout 2
        run: cd posters && typst compile poster-layout2.typ poster-layout2.pdf

      - name: Compile Poster Layout 3
        run: cd posters && typst compile poster-layout3.typ poster-layout3.pdf

      - name: Compile Poster Layout 4
        run: cd posters && typst compile poster-layout4.typ poster-layout4.pdf

      - name: Upload PDF Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-posters
          path: posters/*.pdf
